# Generated by Django 2.0.6 on 2019-03-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo')),
                ('desc', models.CharField(max_length=1000, verbose_name='Descrição')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('1', 'Backlog'), ('2', 'A fazer'), ('3', 'Fazendo'), ('4', 'Feito')], default='1', max_length=30, verbose_name='Status')),
            ],
        ),
    ]
