# Generated by Django 2.0.6 on 2019-03-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='update_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
